// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: nativebpm/v1/workflow.proto

package nativebpmpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nativebpm/connectors/proto/nativebpm/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkflowServiceName is the fully-qualified name of the WorkflowService service.
	WorkflowServiceName = "nativebpm.v1.WorkflowService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkflowServiceStartProcessProcedure is the fully-qualified name of the WorkflowService's
	// StartProcess RPC.
	WorkflowServiceStartProcessProcedure = "/nativebpm.v1.WorkflowService/StartProcess"
	// WorkflowServiceCompleteTaskProcedure is the fully-qualified name of the WorkflowService's
	// CompleteTask RPC.
	WorkflowServiceCompleteTaskProcedure = "/nativebpm.v1.WorkflowService/CompleteTask"
	// WorkflowServiceStreamWorkflowEventsProcedure is the fully-qualified name of the WorkflowService's
	// StreamWorkflowEvents RPC.
	WorkflowServiceStreamWorkflowEventsProcedure = "/nativebpm.v1.WorkflowService/StreamWorkflowEvents"
)

// WorkflowServiceClient is a client for the nativebpm.v1.WorkflowService service.
type WorkflowServiceClient interface {
	StartProcess(context.Context, *connect.Request[v1.StartProcessRequest]) (*connect.Response[v1.StartProcessResponse], error)
	CompleteTask(context.Context, *connect.Request[v1.CompleteTaskRequest]) (*connect.Response[v1.CompleteTaskResponse], error)
	StreamWorkflowEvents(context.Context, *connect.Request[v1.StreamWorkflowEventsRequest]) (*connect.ServerStreamForClient[v1.WorkflowEvent], error)
}

// NewWorkflowServiceClient constructs a client for the nativebpm.v1.WorkflowService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkflowServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkflowServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workflowServiceMethods := v1.File_nativebpm_v1_workflow_proto.Services().ByName("WorkflowService").Methods()
	return &workflowServiceClient{
		startProcess: connect.NewClient[v1.StartProcessRequest, v1.StartProcessResponse](
			httpClient,
			baseURL+WorkflowServiceStartProcessProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("StartProcess")),
			connect.WithClientOptions(opts...),
		),
		completeTask: connect.NewClient[v1.CompleteTaskRequest, v1.CompleteTaskResponse](
			httpClient,
			baseURL+WorkflowServiceCompleteTaskProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("CompleteTask")),
			connect.WithClientOptions(opts...),
		),
		streamWorkflowEvents: connect.NewClient[v1.StreamWorkflowEventsRequest, v1.WorkflowEvent](
			httpClient,
			baseURL+WorkflowServiceStreamWorkflowEventsProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("StreamWorkflowEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workflowServiceClient implements WorkflowServiceClient.
type workflowServiceClient struct {
	startProcess         *connect.Client[v1.StartProcessRequest, v1.StartProcessResponse]
	completeTask         *connect.Client[v1.CompleteTaskRequest, v1.CompleteTaskResponse]
	streamWorkflowEvents *connect.Client[v1.StreamWorkflowEventsRequest, v1.WorkflowEvent]
}

// StartProcess calls nativebpm.v1.WorkflowService.StartProcess.
func (c *workflowServiceClient) StartProcess(ctx context.Context, req *connect.Request[v1.StartProcessRequest]) (*connect.Response[v1.StartProcessResponse], error) {
	return c.startProcess.CallUnary(ctx, req)
}

// CompleteTask calls nativebpm.v1.WorkflowService.CompleteTask.
func (c *workflowServiceClient) CompleteTask(ctx context.Context, req *connect.Request[v1.CompleteTaskRequest]) (*connect.Response[v1.CompleteTaskResponse], error) {
	return c.completeTask.CallUnary(ctx, req)
}

// StreamWorkflowEvents calls nativebpm.v1.WorkflowService.StreamWorkflowEvents.
func (c *workflowServiceClient) StreamWorkflowEvents(ctx context.Context, req *connect.Request[v1.StreamWorkflowEventsRequest]) (*connect.ServerStreamForClient[v1.WorkflowEvent], error) {
	return c.streamWorkflowEvents.CallServerStream(ctx, req)
}

// WorkflowServiceHandler is an implementation of the nativebpm.v1.WorkflowService service.
type WorkflowServiceHandler interface {
	StartProcess(context.Context, *connect.Request[v1.StartProcessRequest]) (*connect.Response[v1.StartProcessResponse], error)
	CompleteTask(context.Context, *connect.Request[v1.CompleteTaskRequest]) (*connect.Response[v1.CompleteTaskResponse], error)
	StreamWorkflowEvents(context.Context, *connect.Request[v1.StreamWorkflowEventsRequest], *connect.ServerStream[v1.WorkflowEvent]) error
}

// NewWorkflowServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkflowServiceHandler(svc WorkflowServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workflowServiceMethods := v1.File_nativebpm_v1_workflow_proto.Services().ByName("WorkflowService").Methods()
	workflowServiceStartProcessHandler := connect.NewUnaryHandler(
		WorkflowServiceStartProcessProcedure,
		svc.StartProcess,
		connect.WithSchema(workflowServiceMethods.ByName("StartProcess")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceCompleteTaskHandler := connect.NewUnaryHandler(
		WorkflowServiceCompleteTaskProcedure,
		svc.CompleteTask,
		connect.WithSchema(workflowServiceMethods.ByName("CompleteTask")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceStreamWorkflowEventsHandler := connect.NewServerStreamHandler(
		WorkflowServiceStreamWorkflowEventsProcedure,
		svc.StreamWorkflowEvents,
		connect.WithSchema(workflowServiceMethods.ByName("StreamWorkflowEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/nativebpm.v1.WorkflowService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkflowServiceStartProcessProcedure:
			workflowServiceStartProcessHandler.ServeHTTP(w, r)
		case WorkflowServiceCompleteTaskProcedure:
			workflowServiceCompleteTaskHandler.ServeHTTP(w, r)
		case WorkflowServiceStreamWorkflowEventsProcedure:
			workflowServiceStreamWorkflowEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkflowServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkflowServiceHandler struct{}

func (UnimplementedWorkflowServiceHandler) StartProcess(context.Context, *connect.Request[v1.StartProcessRequest]) (*connect.Response[v1.StartProcessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("nativebpm.v1.WorkflowService.StartProcess is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) CompleteTask(context.Context, *connect.Request[v1.CompleteTaskRequest]) (*connect.Response[v1.CompleteTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("nativebpm.v1.WorkflowService.CompleteTask is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) StreamWorkflowEvents(context.Context, *connect.Request[v1.StreamWorkflowEventsRequest], *connect.ServerStream[v1.WorkflowEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("nativebpm.v1.WorkflowService.StreamWorkflowEvents is not implemented"))
}
