package ironpress

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"testing"
	"time"
)

func findIronpressBin() string {
	home, err := os.UserHomeDir()
	if err == nil {
		cargoBin := filepath.Join(home, ".cargo", "bin", "ironpress")
		if _, err := os.Stat(cargoBin); err == nil {
			return cargoBin
		}
	}
	return "ironpress"
}

func TestIronpressConnector(t *testing.T) {
	bin := findIronpressBin()

	// 1. Initialize server on dynamic port
	server := NewServer("127.0.0.1:0", bin, 2)

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	serverErrChan := make(chan error, 1)
	go func() {
		if err := server.Start(ctx); err != nil {
			serverErrChan <- err
		}
		close(serverErrChan)
	}()

	// Wait briefly for server to start listening
	time.Sleep(200 * time.Millisecond)

	// Obtain actual listening address
	addr := server.Addr()
	if addr == "" {
		t.Fatal("server address is empty")
	}

	// 2. Test Health Endpoint
	healthURL := fmt.Sprintf("http://%s/health", addr)
	resp, err := http.Get(healthURL)
	if err != nil {
		t.Logf("Health check failed (expected if binary not fully installed yet): %v", err)
	} else {
		defer resp.Body.Close()
		t.Logf("Health check status code: %d", resp.StatusCode)
	}

	// 3. Test Client Fluent API
	client := NewClient(WithHTTP(nil, fmt.Sprintf("http://%s", addr)))

	// Check sticky error for invalid builder operations
	emptyReq := client.Convert(HTTP_CLI_Mode)
	if _, err := emptyReq.Do(ctx); err == nil {
		t.Error("expected error when converting with empty builder state, got nil")
	}

	// Check valid setup (HTML to PDF)
	hasBin := false
	cmdCheck := http.Client{Timeout: 1 * time.Second}
	if hResp, err := cmdCheck.Get(healthURL); err == nil {
		if hResp.StatusCode == http.StatusOK {
			hasBin = true
		}
		hResp.Body.Close()
	}

	if !hasBin {
		t.Log("Skipping live conversion test because ironpress binary is not available or working yet")
		return
	}

	pdfBytes, err := client.Convert(HTTP_CLI_Mode).
		HTML("<html><body><h1>Test document</h1><p>Generated by ironpress connector test</p></body></html>").
		PageSize("a4").
		Landscape(false).
		Margin(10.0).
		Header("Header text").
		Footer("Page {page} of {pages}").
		Timeout(5 * time.Second).
		Do(ctx)

	if err != nil {
		t.Fatalf("conversion failed: %v", err)
	}

	if len(pdfBytes) < 100 {
		t.Errorf("PDF output looks too small: %d bytes", len(pdfBytes))
	}

	if len(pdfBytes) >= 4 && string(pdfBytes[:4]) != "%PDF" {
		t.Errorf("expected PDF header magic, got: %s", string(pdfBytes[:4]))
	}
}
