// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nativebpm/v1/workflow.proto

package nativebpmpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefinitionKey string                 `protobuf:"bytes,1,opt,name=definition_key,json=definitionKey,proto3" json:"definition_key,omitempty"`
	BusinessKey   string                 `protobuf:"bytes,2,opt,name=business_key,json=businessKey,proto3" json:"business_key,omitempty"`
	VariablesJson []byte                 `protobuf:"bytes,3,opt,name=variables_json,json=variablesJson,proto3" json:"variables_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	mi := &file_nativebpm_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nativebpm_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_nativebpm_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *StartProcessRequest) GetDefinitionKey() string {
	if x != nil {
		return x.DefinitionKey
	}
	return ""
}

func (x *StartProcessRequest) GetBusinessKey() string {
	if x != nil {
		return x.BusinessKey
	}
	return ""
}

func (x *StartProcessRequest) GetVariablesJson() []byte {
	if x != nil {
		return x.VariablesJson
	}
	return nil
}

type StartProcessResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	DefinitionHash string                 `protobuf:"bytes,2,opt,name=definition_hash,json=definitionHash,proto3" json:"definition_hash,omitempty"`
	CurrentState   string                 `protobuf:"bytes,3,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	Completed      bool                   `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartProcessResponse) Reset() {
	*x = StartProcessResponse{}
	mi := &file_nativebpm_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse) ProtoMessage() {}

func (x *StartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nativebpm_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse) Descriptor() ([]byte, []int) {
	return file_nativebpm_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *StartProcessResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StartProcessResponse) GetDefinitionHash() string {
	if x != nil {
		return x.DefinitionHash
	}
	return ""
}

func (x *StartProcessResponse) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

func (x *StartProcessResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	VariablesJson []byte                 `protobuf:"bytes,3,opt,name=variables_json,json=variablesJson,proto3" json:"variables_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_nativebpm_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nativebpm_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_nativebpm_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteTaskRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CompleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CompleteTaskRequest) GetVariablesJson() []byte {
	if x != nil {
		return x.VariablesJson
	}
	return nil
}

type CompleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	CurrentState  string                 `protobuf:"bytes,2,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskResponse) Reset() {
	*x = CompleteTaskResponse{}
	mi := &file_nativebpm_v1_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskResponse) ProtoMessage() {}

func (x *CompleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nativebpm_v1_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_nativebpm_v1_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteTaskResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CompleteTaskResponse) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

func (x *CompleteTaskResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

var File_nativebpm_v1_workflow_proto protoreflect.FileDescriptor

const file_nativebpm_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1bnativebpm/v1/workflow.proto\x12\fnativebpm.v1\x1a\x1cgoogle/api/annotations.proto\"\x86\x01\n" +
	"\x13StartProcessRequest\x12%\n" +
	"\x0edefinition_key\x18\x01 \x01(\tR\rdefinitionKey\x12!\n" +
	"\fbusiness_key\x18\x02 \x01(\tR\vbusinessKey\x12%\n" +
	"\x0evariables_json\x18\x03 \x01(\fR\rvariablesJson\"\xa3\x01\n" +
	"\x14StartProcessResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12'\n" +
	"\x0fdefinition_hash\x18\x02 \x01(\tR\x0edefinitionHash\x12#\n" +
	"\rcurrent_state\x18\x03 \x01(\tR\fcurrentState\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\bR\tcompleted\"v\n" +
	"\x13CompleteTaskRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12%\n" +
	"\x0evariables_json\x18\x03 \x01(\fR\rvariablesJson\"z\n" +
	"\x14CompleteTaskResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rcurrent_state\x18\x02 \x01(\tR\fcurrentState\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted2\xaf\x02\n" +
	"\x0fWorkflowService\x12\x8c\x01\n" +
	"\fStartProcess\x12!.nativebpm.v1.StartProcessRequest\x1a\".nativebpm.v1.StartProcessResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/nativebpm.v1.WorkflowService/StartProcess\x12\x8c\x01\n" +
	"\fCompleteTask\x12!.nativebpm.v1.CompleteTaskRequest\x1a\".nativebpm.v1.CompleteTaskResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/nativebpm.v1.WorkflowService/CompleteTaskB@Z>github.com/nativebpm/connectors/proto/nativebpm/v1;nativebpmpbb\x06proto3"

var (
	file_nativebpm_v1_workflow_proto_rawDescOnce sync.Once
	file_nativebpm_v1_workflow_proto_rawDescData []byte
)

func file_nativebpm_v1_workflow_proto_rawDescGZIP() []byte {
	file_nativebpm_v1_workflow_proto_rawDescOnce.Do(func() {
		file_nativebpm_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nativebpm_v1_workflow_proto_rawDesc), len(file_nativebpm_v1_workflow_proto_rawDesc)))
	})
	return file_nativebpm_v1_workflow_proto_rawDescData
}

var file_nativebpm_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nativebpm_v1_workflow_proto_goTypes = []any{
	(*StartProcessRequest)(nil),  // 0: nativebpm.v1.StartProcessRequest
	(*StartProcessResponse)(nil), // 1: nativebpm.v1.StartProcessResponse
	(*CompleteTaskRequest)(nil),  // 2: nativebpm.v1.CompleteTaskRequest
	(*CompleteTaskResponse)(nil), // 3: nativebpm.v1.CompleteTaskResponse
}
var file_nativebpm_v1_workflow_proto_depIdxs = []int32{
	0, // 0: nativebpm.v1.WorkflowService.StartProcess:input_type -> nativebpm.v1.StartProcessRequest
	2, // 1: nativebpm.v1.WorkflowService.CompleteTask:input_type -> nativebpm.v1.CompleteTaskRequest
	1, // 2: nativebpm.v1.WorkflowService.StartProcess:output_type -> nativebpm.v1.StartProcessResponse
	3, // 3: nativebpm.v1.WorkflowService.CompleteTask:output_type -> nativebpm.v1.CompleteTaskResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nativebpm_v1_workflow_proto_init() }
func file_nativebpm_v1_workflow_proto_init() {
	if File_nativebpm_v1_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nativebpm_v1_workflow_proto_rawDesc), len(file_nativebpm_v1_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nativebpm_v1_workflow_proto_goTypes,
		DependencyIndexes: file_nativebpm_v1_workflow_proto_depIdxs,
		MessageInfos:      file_nativebpm_v1_workflow_proto_msgTypes,
	}.Build()
	File_nativebpm_v1_workflow_proto = out.File
	file_nativebpm_v1_workflow_proto_goTypes = nil
	file_nativebpm_v1_workflow_proto_depIdxs = nil
}
